### ISSUE TITLE
Game crashed after trying to load single player world after playing on the official server

### ISSUE THREAD

**Issue by Dr-Game** [SmashingMods/antimatter-chemistry#167] opened 2019-08-04 15:37 UTC
Crash report
[crash-2019-08-04_10.30.31-server.txt](https://github.com/al132mc/antimatter-chemistry/files/3465033/crash-2019-08-04_10.30.31-server.txt)

**Comment by al132mc** [comment] 2019-08-06 14:05
I do see this crash from time to time, but usually starting up the game and trying to open the world will resolve it...

**Comment by Dr-Game** [comment] 2019-08-06 16:01
Yeah, it's just a minor annoyance. It doesn't take but a few minutes to relaunch the game for me, but a crash is still a crash, and I thought reporting it would help.

**Comment by MasterEnderman** [comment] 2022-05-05 23:40
Duplicate of #44

**Closed by MasterEnderman** 2022-05-05 23:40 UTC
Labels: Crash Bug, duplicate, Mod Bug
