### ISSUE TITLE
Game crashed while in Crafting station

### ISSUE THREAD

**Issue by DragonFyreStorm** [SmashingMods/antimatter-chemistry#177] opened 2019-08-10 22:31 UTC
[crash-2019-08-10_18.02.52-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3489338/crash-2019-08-10_18.02.52-client.txt)
[crash-2019-08-10_18.12.41-client.txt](https://github.com/al132mc/antimatter-chemistry/files/3489339/crash-2019-08-10_18.12.41-client.txt)

**Comment by al132mc** [comment] 2019-08-10 23:09
Known bug that has something to do with specifically crafting compressed cobble in the crafting station, for some reason...

**Comment by TheSnowyChickens** [comment] 2019-08-15 20:11
Also other types of blocks produce the crash. :(

**Comment by MasterEnderman** [comment] 2022-05-04 23:17
Duplicate of #161

**Closed by MasterEnderman** 2022-05-04 23:17 UTC
Labels: duplicate, Mod Bug
